_partial_: True
_target_: method.Composer
lr: 0.001
retaingraph: True
plugins:
  - _target_: method.interval_penalization_mlp_with_learnable_relu.MLPWithLearnableReLUIntervalPenalization
    var_scale: 0.01
    lambda_int_drift: 0.0001
    lambda_int_input: 0.0001
    dil_mode: False
    regularize_classifier: True
    reduced_dim: 30