from .composer import Composer
from .lwf import LwF
from .ewc import EWC
from .mas import MAS
from .si import SI
from .interval_penalization_resnet18_last_block import ResNet18IntervalPenalizationLastBlock
from .interval_penalization_resnet18_cls import ResNet18IntervalPenalizationCls
from .interval_penalization_mlp import MLPIntervalPenalization
from .interval_penalization_big_model import BigModelIntervalPenalization